export const columns = [
  {
    key: "inspector",
    label: "Inspector",
  },
  {
    key: "id",
    label: "ID",
  },
  {
    key: "institution",
    label: "Institution",
  },
  {
    key: "branch",
    label: "Sucursal",
  },
  {
    key: "service",
    label: "Servicio",
  },
  {
    key: "department",
    label: "Departamento",
  },
  {
    key: "assigned_to",
    label: "Asignado a",
  },
  {
    key: "manufacturer",
    label: "Fabricante",
  },
  {
    key: "garment_type",
    label: "Tipo de elemento",
  },
  {
    key: "core_material",
    label: "Material principal",
  },
  {
    key: "size",
    label: "Talle",
  },
  {
    key: "protection_level",
    label: "Nivel de protección",
  },
  {
    key: "color_trim",
    label: "Color/trim",
  },
  {
    key: "manufactured",
    label: "Fecha de fabricación",
  },
  {
    key: "notes",
    label: "Notas",
  },
  {
    key: "last_inspection",
    label: "Ultima inspección",
  },
  {
    key: "inspection_result",
    label: "Resultado de la inspección",
  },
  {
    key: "next_inspection",
    label: "Próxima inspección",
  },
  {
    key: "status",
    label: "Status",
  },
];

export const rows = [
  {
    key: "1",
    inspector: "Juan Pérez",
    id: "EPP-001",
    institution: "Hospital Central",
    branch: "Sede Norte",
    service: "Mantenimiento",
    department: "Seguridad e Higiene",
    assigned_to: "Carlos Gómez",
    manufacturer: "3M",
    garment_type: "Casco de seguridad",
    core_material: "Policarbonato",
    size: "M",
    protection_level: "Alto",
    color_trim: "Blanco",
    manufactured: "2023-05-12",
    notes: "En buen estado general",
    last_inspection: "2024-12-01",
    inspection_result: "Aprobado",
    next_inspection: "2025-06-01",
    status: "Activo",
  },
  {
    key: "2",
    inspector: "Laura Torres",
    id: "EPP-002",
    institution: "Fábrica Metalúrgica Sur",
    branch: "Planta 2",
    service: "Producción",
    department: "Operaciones",
    assigned_to: "María López",
    manufacturer: "Uvex",
    garment_type: "Gafas de protección",
    core_material: "Policarbonato",
    size: "Único",
    protection_level: "Medio",
    color_trim: "Negro",
    manufactured: "2022-11-08",
    notes: "Ligeros rayones",
    last_inspection: "2024-09-10",
    inspection_result: "Aprobado con observaciones",
    next_inspection: "2025-03-10",
    status: "Activo",
  },
  {
    key: "3",
    inspector: "Diego Martínez",
    id: "EPP-003",
    institution: "Laboratorio BioLab",
    branch: "Sede Central",
    service: "Investigación",
    department: "Bioseguridad",
    assigned_to: "Sofía Ramírez",
    manufacturer: "Dupont",
    garment_type: "Guantes de nitrilo",
    core_material: "Nitrilo",
    size: "L",
    protection_level: "Alto",
    color_trim: "Azul",
    manufactured: "2024-02-14",
    notes: "Stock limitado",
    last_inspection: "2024-08-20",
    inspection_result: "Aprobado",
    next_inspection: "2025-02-20",
    status: "Activo",
  },
  {
    key: "4",
    inspector: "Marta Fernández",
    id: "EPP-004",
    institution: "Constructora Andina",
    branch: "Obra Puerto Madero",
    service: "Construcción",
    department: "Campo",
    assigned_top: "Ricardo Díaz",
    manufacturer: "SteelPro",
    garment_type: "Arnés de seguridad",
    core_material: "Poliéster",
    size: "XL",
    protection_level: "Crítico",
    color_trim: "Negro",
    manufactured: "2023-03-30",
    notes: "Correas revisadas y ajustadas",
    last_inspection: "2025-01-05",
    inspection_result: "Aprobado",
    next_inspection: "2025-07-05",
    status: "Activo",
  },
];
